apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argo-helm-alejo
  annotations:
    github.com/project-slug: arboleda-alejandro/argo-helm-alejo
    backstage.io/techdocs-ref: dir:.
  description: Community-maintained Helm charts for Argo projects (ArgoCD, Argo Workflows, Argo Rollouts). Fork of argoproj/argo-helm.
spec:
  type: library
  lifecycle: experimental
  owner: user:default/arboleda-alejandro
  system: gitops-platform

